<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <ApplicationIcon>Assets\launcher-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\launcher-background.png" />
    <Resource Include="Assets\video-cooperation.png" />
    <Resource Include="Assets\video-interlude-vs-classic.png" />
    <Resource Include="Assets\launcher-icon.ico" />
    <Resource Include="Assets\launcher-icon.png" />
  </ItemGroup>

</Project>